Fix packaging error
Collecting arviz
  Downloading arviz-0.11.3-py3-none-any.whl (1.6 MB)
ERROR: Cannot install -r requirements.txt (line 10) because these package versions have conflicting dependencies.

The conflict is caused by:
    numpyro 0.8.0 depends on jaxlib>=0.1.65

	modified:   requirements.txt