Removing numpyro requirement due to errors
ERROR: Could not find a version that satisfies the requirement jaxlib>=0.1.65 (from numpyro) (from versions: none)
ERROR: No matching distribution found for jaxlib>=0.1.65

	modified:   requirements.txt